version: 0.2
    
phases:
  install:
    commands:
      # Update sam to latest version
      - wget -q https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      - unzip -q awscli-exe-linux-x86_64.zip
      - sudo ./aws/install --update
      - rm -rf ./aws  awscli-exe-linux-x86_64.zip

  pre_build: 
    commands:
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

  build:
    commands:
      - TemplateBody="$(cat $TemplatePath)"
      - Parameters="$(cat $ParameterPath)"
      - Capabilities="CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM, CAPABILITY_IAM"

      - aws assume-role --role-arn "${ProductionAcctCodePipelineCloudFormationRole}" --role-session-name "CloudFormationRole"

      # Create a changeset for the deployment
      - aws cloudformation create-change-set --stack-name "${StackName}" --template-body "${TemplateBody}" --parameters "${Parameters}" --role-arn "${CloudFormationDeployerRole}" --change-set-name "${ChangeSetName}" --change-set-type "CREATE"

      # Deploy the changeset
      - aws cloudformation execute-change-set \
        --change-set-name "${ChangeSetName}"
        
