AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 
  This CloudFormation template will deploy an instance of the SSOSync-Staging
  candidate releases (via privately shared app in the AWS Serverless Application
  Repository (SAR) within the Staging Account.

Resources:
  SARApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: '{{resolve:ssm:SSOSync/Staging/AppArn}}'
        SemanticVersion: '{{resolve:ssm:SSOSync/Staging/Version}}'
      Parameters:
        GoogleAdminEmail: '{{resolve:secretsmanager:TestGoogleAdminEmail}}'
        GoogleCredentials: '{{resolve:secretsmanager:TestGoogleCredentials}}'
        SCIMEndpointUrl: '{{resolve:secretsmanager:TestSCIMEndpointUrl}}'
        SCIMEndpointAccessToken: '{{resolve:secretsmanager:TestSCIMAccessToken}}'
        SyncMethod: groups
        GoogleUserMatch: 'name:*'
        GoogleGroupMatch: 'name:AWS*'
        LogLevel: warn
        LogFormat: json
        IgnoreUsers: None
        IgnoreGroups: None
        IncludeGroups: None
        ScheduleExpression: 'rate(1 day)'

  FunctionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/SSOSync/Staging/FunctionArn"
      Type: String
      Value: !GetAtt SARApp.Outputs.FunctionArn
      Description: The Arn of the lambda function ssosync
 
Outputs:
  FunctionArn:
    Description: "The Arn of the deployed lambda function"
    Value: !GetAtt SARApp.Outputs.FunctionArn
    Export:
      Name: FunctionArn
