version: 0.2
            
env:
  variables:
    GO_VERSION: "1.18.1"
    OUTPUT: main
    TEMPLATE: template.yaml
    PACKAGED_TEMPLATE: packaged.yaml
    APP_NAME: ssosync
phases:
  install: 
    commands:
      # Install go.lang
      - wget https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C / -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH="/go/bin:$PATH" && export GOPATH="/go" && export PATH="$GOPATH/bin:$PATH"
      - rm go${GO_VERSION}.linux-amd64.tar.gz

      # Install golint
      - go install golang.org/x/lint/golint@latest

      # Install staticcheck
      - go install honnef.co/go/tools/cmd/staticcheck@latest

      # Install Testify to use common assertions and mocks in tests
      - go get -u github.com/stretchr/testify

      # Install goreleaser
      - go install github.com/goreleaser/goreleaser@latest

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

      # Update sam to latest version
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install --update
      - rm -rf ./sam-installation  aws-sam-cli-linux-x86_64.zip

  pre_build: 
    commands:
      # Fetch all dependencies
      - go env -w GOPROXY=direct
      - go get ./...

      # Run staticcheck
      - staticcheck ./...

      # Ensure code passes all lint tests
      #- golint -set_exit_status ./...

      # Check the Go code for common problems with 'go vet'
      - go vet ./...

      # Run all tests included with our application
      - go test ./...

  build:
    commands:
      # Make clean
      - rm -f ${OUTPUT} ${PACKAGED_TEMPLATE}

      # Make go-build
      - go build -o ${APP_NAME} main.go
 
      # Make main 
      - goreleaser build --snapshot --rm-dist

      # Package our application with AWS SAM
      - sam package --s3-bucket ${S3BUCKET} 

  post_build:
    commands:
      - ls -la 

artifacts:
  files:
    - packaged.yaml
