AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 
  This CloudFormation template will deploy a full CI/CD pipeline for SSO
  Sync. It includes building with AWS CodeBuild, publishing to a
  staging (private) AWS Serverless Application Repository (SAR), deployment
  of the beta into a staging environment via AWS CloudFormation. If the commit
  is also a release, then the app will also be published to the public SAR entry.

Parameters:
  ApplicationName: 
    Description: This will be used to name the pipeline and build resources
    Default: SSOSync
    Type: String
    AllowedPattern: '[A-Za-z0-9-]+'
  StagingAccount:
    Description: AWS Account where staging build is automatically deployed and tested
    Type: String
    AllowedPattern: '[0-9]+'
  CodeStarConnection:
    Description:  Resource ARN for the CodeStar Connection to use
    Type: String
    AllowedPattern: '[A-Za-z0-9:/-]+'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: Application Configuration
        Parameters:
          - ApplicationName
      - Label:
          default: End 2 End Test environment
        Parameters:
          - StagingAccount
      - Label:
          default: Connection id for the CodeStar Connection to use
        Parameters:
          - CodeStarConnection
            
    ParameterLabels:
      ApplicationName: 
        default: "SSOSync"
      StagingAccount:
        default: "716793247609"

Resources:

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: debug-deplyment
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/SSOSync-CodePipeline-us-east-2
      ArtifactStore: 
        Type: S3
        Location: release-artifactbucket-u7m2j1gyyjko
        EncryptionKey: 
          Type: KMS
          Id: arn:aws:kms:us-east-2:004480582608:key/3fda4b9a-48e8-4d81-bf52-7da62f69d85e
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: Source
              RunOrder: '1'
              Configuration:
                ConnectionArn: arn:aws:codestar-connections:us-east-2:004480582608:connection/0a1c90d5-1395-4a3b-8734-2b53cda9fad2
                FullRepositoryId: awslabs/ssosync
                BranchName: CodePipeline
                DetectChanges: true
        - Name: Staging
          Actions:
            - Name: CreateChangeSetTest
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub Deploy-${ApplicationName}
                ActionMode: CHANGE_SET_REPLACE
                StackName: SmokeTest
                Capabilities: CAPABILITY_IAM,CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: 'Source::cicd/deploy/stack.yml' 
                RoleArn: !Sub arn:aws:iam::${StagingAccount}:role/CloudFormationDeployerRole
                ParameterOverrides: !Sub '{"ApplicationArn": "arn:aws:serverlessrepo:${AWS::Region}:${AWS::AccountId}:applications/${ApplicationName}-Staging"}'
                OutputFileName: 'stack-outputs.json'
              InputArtifacts:
                - Name: Source
              RunOrder: 1
              RoleArn: !Sub arn:aws:iam::${StagingAccount}:role/ProductionAcctCodePipelineCloudFormationRole
            - Name: DeployChangeSetTest
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub Deploy-${ApplicationName}
                ActionMode: CHANGE_SET_EXECUTE
                StackName: SmokeTest
                RoleArn: !Sub arn:aws:iam::${StagingAccount}:role/CloudFormationDeployerRole
              InputArtifacts:
                - Name: Source
              RunOrder: 2
              RoleArn: !Sub arn:aws:iam::${StagingAccount}:role/ProductionAcctCodePipelineCloudFormationRole
            - Name: ManualTesting
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              RunOrder: 3
            - Name: CleanUp
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: DELETE_ONLY
                StackName: SmokeTest
                RoleArn: !Sub arn:aws:iam::${StagingAccount}:role/CloudFormationDeployerRole
              InputArtifacts:
                - Name: Source
              RunOrder: 4

