version: 0.2

phases:
  install:
    commands:
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

      # Update sam to latest version
      - wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install --update
      - rm -rf ./sam-installation  aws-sam-cli-linux-x86_64.zip
  
  pre_build:
    commands:
      - cp -r ${CODEBUILD_SRC_DIR_Built}/* ./
      - ls -la

      # Check that the files need to package exist
      - ls README.md
      - ls SAR.md
      - ls dist/ssosync_linux_amd64_v1/ssosync
 
      # Check that the executable works
      - ./dist/ssosync_linux_amd64_v1/ssosync --version 

  build:
    commands:
      # Package our application with AWS SAM
      - sam package --no-progressbar --template-file template.yaml --s3-bucket ${S3Bucket} --output-template-file packaged.yaml

  post_build:
    commands:
      - ls packaged.yaml

artifacts:
  files:
    - packaged.yaml
