
# .github/workflows/main.yaml
name: main

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0

      - name: Run Tests
        run: go test -cover -p 1 -race -v ./...
